TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devlitron.db
DB += devlitron.proto

#=======================================
include $(TOP)/configure/RULES
