TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += litron.db
DB += litron_logic.db

#=======================================
include $(TOP)/configure/RULES
